language: java

#default depth is 50, unnecessary
git:
    depth: 1

jdk:
    - oraclejdk8
    - oraclejdk9

#concurrently build on jdk8 and jdk9, but allow jdk9 failures to not impact the build status
matrix:
    allow_failures:
    - jdk: oraclejdk9
    fast_finish: true

#before_install:
#   - jdk_switcher use oraclejdk8

script:
    - mvn clean verify -B
