language: java

#default depth is 50, unnecessary
git:
    depth: 1

sudo: false
  
matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: osx
      osx_image: xcode8

script:
    - mvn clean verify -B

cache:
    directories:
    - $HOME/.m2
    - $HOME/.binaries
