language: java

#default depth is 50, unnecessary
git:
    depth: 1

sudo: false
  
matrix:
  include:
    - os: linux
      jdk: oraclejdk8
      before_install:
      - ./build-tools/src/main/resources/bash/travis-download-maven.sh
      - export M2_HOME=$HOME/.binaries/apache-maven-3.3.9
      - export PATH=$M2_HOME/bin:$PATH
      - mvn -Xmx32m --version
      - echo "MAVEN_OPTS=\"$MAVEN_OPTS -XX:+CMSClassUnloadingEnabled -Xmx1g\"" > $HOME/.mavenrc
    - os: osx
      osx_image: xcode8
      before_install:
      - ./build-tools/src/main/resources/bash/travis-download-maven.sh
      - export M2_HOME=$HOME/.binaries/apache-maven-3.3.9
      - export PATH=$M2_HOME/bin:$PATH
      - mvn -Xmx32m --version
      - echo "MAVEN_OPTS=\"$MAVEN_OPTS -XX:+CMSClassUnloadingEnabled -Xmx1g -Dmaven.test.skip=true -Dcheckstyle.skip=true\"" > $HOME/.mavenrc

#writes version of linux/macOS to log
before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sw_vers -productVersion; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then uname -r; fi

script:
    - mvn clean verify -B

cache:
    directories:
    - $HOME/.m2
    - $HOME/.binaries
