language: java

#default depth is 50, unnecessary
git:
    depth: 1

sudo: false
  
matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: osx
      osx_image: xcode8
      
#writes version of linux/macOS to log
before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sw_vers -productVersion; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then uname -r; fi

script:
    - mvn clean verify -B

cache:
    directories:
    - $HOME/.m2
    - $HOME/.binaries
