language: java

sudo: false
  
matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: osx
      osx_image: xcode8

script:
    - mvn clean verify -B

cache:
    directories:
    - $HOME/.m2
