version: '{build}'
os: Windows Server 2012
install:
  - cmd: mvn --version
  - cmd: java -version
build_script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
test_script:
  - mvn verify -B
cache:
  - C:\Users\appveyor\.m2
